name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Make scripts executable
      run: |
        chmod +x scripts/build.sh
        chmod +x scripts/deploy.sh
    
    - name: Build
      run: ./scripts/build.sh
    
    - name: Deploy
      run: ./scripts/deploy.sh